# Generated by Django 3.2.25 on 2026-05-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsVector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('news_id', models.IntegerField(db_index=True, unique=True, verbose_name='新闻ID')),
                ('vector_data', models.TextField(blank=True, null=True, verbose_name='向量数据(JSON格式)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '新闻向量',
                'verbose_name_plural': '新闻向量',
                'db_table': 'news_api_newsvector',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QAHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('userid', models.IntegerField(db_index=True, verbose_name='用户ID')),
                ('newsid', models.IntegerField(db_index=True, verbose_name='新闻ID')),
                ('question', models.TextField(verbose_name='用户问题')),
                ('answer', models.TextField(verbose_name='系统回答')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='问答时间')),
            ],
            options={
                'verbose_name': '问答历史',
                'verbose_name_plural': '问答历史',
                'db_table': 'news_api_qahistory',
                'ordering': ['-time'],
            },
        ),
        migrations.AddIndex(
            model_name='qahistory',
            index=models.Index(fields=['userid'], name='idx_userid'),
        ),
        migrations.AddIndex(
            model_name='qahistory',
            index=models.Index(fields=['newsid'], name='idx_newsid'),
        ),
        migrations.AddIndex(
            model_name='qahistory',
            index=models.Index(fields=['time'], name='idx_time'),
        ),
    ]
