# Generated by Django 3.1.14 on 2026-07-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0002_auto_20260511_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_index=True)),
                ('role', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('intent_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news_api_agent_conversation',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentconversation',
            index=models.Index(fields=['userid', 'created_at'], name='news_api_ag_userid_30897a_idx'),
        ),
    ]
