# Generated by Django 3.1.14 on 2026-07-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0003_auto_20260707_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_summary_memory',
            field=models.TextField(blank=True, null=True, verbose_name='Agent长期记忆摘要'),
        ),
    ]
